### ISSUE TITLE
🐛 cannot build for android

### ISSUE THREAD

**Issue by ElecTwix** [dotintent/react-native-ble-plx#1170]
### Prerequisites

- [X] I checked the documentation and FAQ without finding a solution
- [X] I checked to make sure that this issue has not already been filed

### Expected Behavior

build and run on Android device

### Current Behavior

Getting the error when building for android

### Library version

3.1.2

### Device

Any Android

### Environment info

```shell
info Fetching system and libraries information...
(node:91736) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
System:
  OS: Linux 6.7 Arch Linux
  CPU: (12) x64 AMD Ryzen 5 5600 6-Core Processor
  Memory: 47.77 GB / 62.72 GB
  Shell:
    version: "5.9"
    path: /usr/bin/zsh
Binaries:
  Node:
    version: 21.6.1
    path: /usr/bin/node
  Yarn:
    version: 1.22.21
    path: /usr/bin/yarn
  npm:
    version: 10.4.0
    path: /usr/bin/npm
  Watchman: Not Found
SDKs:
  Android SDK:
    API Levels:
      - "33"
      - "34"
    Build Tools:
      - 33.0.1
      - 34.0.0
    System Images:
      - android-30 | Google Play Intel x86 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: AI-231.9392.1.2311.11330709
Languages:
  Java:
    version: 21.0.2
    path: /usr/bin/javac
  Ruby:
    version: 3.0.6
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.73.2
    wanted: 0.73.2
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false

info React Native v0.73.3 is now available (your project is running on v0.73.2).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.73.3
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.73.3
info For more info, check out "https://reactnative.dev/docs/upgrading?os=linux".
```

### Steps to reproduce

1. `npx create-expo-app my-app`
2. add [Configuration & Installation](https://github.com/dotintent/react-native-ble-plx?tab=readme-ov-file#configuration--installation)
3. `npx expo prebuild`
4. `npx expo run:android`

### Formatted code sample or link to a repository

```js
didn't add anything custom just created clean expo app
openjdk 21.0.2 2024-01-16
OpenJDK Runtime Environment (build 21.0.2+13)
OpenJDK 64-Bit Server VM (build 21.0.2+13, mixed mode, sharing)
```

### Relevant log output

```shell
› Building app...
Configuration on demand is an incubating feature.

> Configure project :expo

Using expo modules
  - expo-constants (15.4.5)
  - expo-file-system (16.0.5)
  - expo-font (11.10.2)
  - expo-keep-awake (12.8.2)
  - expo-modules-core (1.11.8)
  - expo-modules-core$android-annotation (1.11.8)
  - expo-modules-core$android-annotation-processor (1.11.8)


> Task :react-native-ble-plx:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-ble-plx:compileDebugJavaWithJavac'.
> Could not resolve all files for configuration ':react-native-ble-plx:androidJdkImage'.
   > Failed to transform core-for-system-modules.jar to match attributes {artifactType=_internal_android_jdk_image, org.gradle.libraryelements=jar, org.gradle.usage=java-runtime}.
      > Execution failed for JdkImageTransform: /opt/android-sdk/platforms/android-34/core-for-system-modules.jar.
         > Error while executing process /usr/lib/jvm/java-21-openjdk/bin/jlink with arguments {--module-path /home/electwix/.gradle/caches/transforms-3/df8a4d771b7ddfe0ae4b0751ab94f2d7/transformed/output/temp/jmod --add-modules java.base --output /home/electwix/.gradle/caches/transforms-3/df8a4d771b7ddfe0ae4b0751ab94f2d7/transformed/output/jdkImage --disable-plugin system-modules}

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.3/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 4s
117 actionable tasks: 3 executed, 2 from cache, 112 up-to-date
Error: /home/electwix/dev/ts/my-app/android/gradlew exited with non-zero code: 1
Error: /home/electwix/dev/ts/my-app/android/gradlew exited with non-zero code: 1
    at ChildProcess.completionListener (/home/electwix/dev/ts/my-app/node_modules/@expo/spawn-async/build/spawnAsync.js:52:23)
    at Object.onceWrapper (node:events:634:26)
    at ChildProcess.emit (node:events:519:28)
    at maybeClose (node:internal/child_process:1105:16)
    at ChildProcess._handle.onexit (node:internal/child_process:305:5)
    ...
    at Object.spawnAsync [as default] (/home/electwix/dev/ts/my-app/node_modules/@expo/spawn-async/build/spawnAsync.js:17:21)
    at spawnGradleAsync (/home/electwix/dev/ts/my-app/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:72:46)
    at Object.assembleAsync (/home/electwix/dev/ts/my-app/node_modules/@expo/cli/build/src/start/platforms/android/gradle.js:52:18)
    at runAndroidAsync (/home/electwix/dev/ts/my-app/node_modules/@expo/cli/build/src/run/android/runAndroidAsync.js:36:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Additional information

openjdk 21.0.2 2024-01-16
OpenJDK Runtime Environment (build 21.0.2+13)
OpenJDK 64-Bit Server VM (build 21.0.2+13, mixed mode, sharing)

**Comment by ElecTwix** [comment]
using
```
openjdk 17.0.10 2024-01-16
OpenJDK Runtime Environment (build 17.0.10+7)
OpenJDK 64-Bit Server VM (build 17.0.10+7, mixed mode)
``` 
solved the issue
