### ISSUE TITLE
null object reference error on multiplatformbleadapter.bleadapter.getcurrentstate()

### ISSUE THREAD

**Issue by soumyarath** [dotintent/react-native-ble-plx#847]
## Prerequisites
![MicrosoftTeams-image](https://user-images.githubusercontent.com/17500886/118909945-e0481800-b977-11eb-8572-726036bfd9d7.png)

Please answer the following questions for yourself before submitting an issue. **YOU MAY DELETE THE PREREQUISITES SECTION.**

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm sure that question is related to the library itself and not Bluetooth Low Energy or Classic in general. If that so, please post your question on [StackOverflow](https://stackoverflow.com/questions/tagged/react-native-ble-plx?sort=active) or on our [Gitter](https://gitter.im/RxBLELibraries/react-native-ble) channel.

## Question

This happens intermittently after I upgraded to the latest react-native and react-native-ble-plx.
package.json:

"dependencies": {
    "@react-native-community/async-storage": "^1.6.3",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/toolbar-android": "0.1.0-rc.2",
    "@react-native-picker/picker": "^1.12.0",
    "@sentry/react-native": "^1.6.2",
    "js-base64": "^2.5.1",
    "native-base": "^2.15.2",
    "prop-types": "^15.7.2",
    "react": "17.0.1",
    "react-native": "0.64.0",
    "react-native-appstore-version-checker": "^3.0.0",
    "react-native-ble-plx": "^2.0.2",
    "react-native-camera": "^3.11.1",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-indicators": "^0.17.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-material-dialog": "^0.7.7",
    "react-native-permissions": "^3.0.2",
    "react-native-progress-steps": "^1.3.4",
    "react-native-qrcode-scanner": "^1.5.4",
    "react-native-reanimated": "^1.9.0",
    "react-native-router-flux": "^4.3.1",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^2.10.1",
    "react-native-size-matters": "^0.3.0",
    "react-native-splash-screen": "^3.2.0",
    "react-native-uuid-generator": "^6.1.1",
    "react-native-vector-icons": "^8.1.0",
    "realm": "^3.6.5"
  },
  "devDependencies": {
    "@babel/core": "7.7.2",
    "@babel/runtime": "7.7.2",
    "@react-native-community/eslint-config": "0.0.5",
    "babel-jest": "24.9.0",
    "eslint": "6.6.0",
    "jest": "24.9.0",
    "metro-react-native-babel-preset": "0.56.3",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  }

Error:

2021-05-20 14:34:27.491 26666-28416/com.corehub_install_app E/unknown:ReactNative: Exception in native call
    java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String com.polidea.multiplatformbleadapter.BleAdapter.getCurrentState()' on a null object reference
        at com.polidea.reactnativeble.BleClientManager.state(BleClientManager.java:156)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:214)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:919)

**Comment by soumyarath** [comment]
@sunilloharshoreline1 that's correct. I resolved this issue a while back and forgot that I asked a question here. Closing it now :)
