### ISSUE TITLE
Bug Report : cannot start scanning on Android 12 - A52 phone

### ISSUE THREAD

**Issue by bogguard** [dotintent/react-native-ble-plx#998]
## Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Expected Behavior

The start scanning operation doesn't work on Android 12, phone Galaxy A52s 5G (SM-A528B/DS).
It does work on every iPhone I've tested and an older Android 8 phone Galaxy A5 (SM-A520F)
I expect it to work on the latest Android phones as well.

## Current Behavior

When scanning I receive the following error : 
```
Cannot start scanning operation
at http://192.168.0.243:8081/index.bundle?platform=android&dev=true&minify=false&app=xxx.xxx.xxx&modulesOnly=false&runModule=true:121060:321 in _createSuperInternal
at node_modules/react-native-ble-plx/src/BleError.js:47:4 in constructor
at node_modules/react-native-ble-plx/src/BleError.js:75:15 in parseBleError
at node_modules/react-native-ble-plx/src/BleManager.js:339:16 in scanListener
at node_modules/react-native/Libraries/vendor/emitter/_EventEmitter.js:150:10 in EventEmitter#emit
``` 

The Location button is activated on the Android top menu. All location permissions are given to the application.
The manifest contains the following :
```
<uses-permission-sdk-23 android:name="android.permission.ACCESS_FINE_LOCATION"/>
<uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
<uses-permission android:name="android.permission.BLUETOOTH"/>
<uses-permission android:name="android.permission.BLUETOOTH_ADMIN"/>
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `expo init`
2. `expo add react-native-ble-plx @config-plugins/react-native-ble-plx expo-dev-client`
3. Add `@config-plugins/react-native-ble-plx` to the expo.plugins array in your `app.json`.
4. Make a button and scan the devices.
5. Run it through `eas`or `expo run:android`

### Context

* Library version: 2.0.3
* Platform: Android 12
* JS logs:
```
Cannot start scanning operation
at http://192.168.0.243:8081/index.bundle?platform=android&dev=true&minify=false&app=xxx.xxx.xxx&modulesOnly=false&runModule=true:121060:321 in _createSuperInternal
at node_modules/react-native-ble-plx/src/BleError.js:47:4 in constructor
at node_modules/react-native-ble-plx/src/BleError.js:75:15 in parseBleError
at node_modules/react-native-ble-plx/src/BleManager.js:339:16 in scanListener
at node_modules/react-native/Libraries/vendor/emitter/_EventEmitter.js:150:10 in EventEmitter#emit
```
* Contents of the `package.json` file:
```
{
  "name": "test-ble",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@config-plugins/react-native-ble-plx": "^2.0.0",
    "expo": "~45.0.0",
    "expo-dev-client": "~1.0.1",
    "expo-status-bar": "~1.3.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-ble-plx": "^2.0.3",
    "react-native-web": "0.17.7",
    "expo-splash-screen": "~0.15.1"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.66.13",
    "typescript": "~4.3.5"
  },
  "private": true
}
```

* Formatted code sample or link to a repository:

```js
requestBluetoothPermissionAsync()
    .then(() => {
      BluetoothManager.startDeviceScan(null, null, (error, device) => {
        if (error) {
          // Handle error (scanning will be stopped automatically), this gets hit on the Android Galaxy A52
          console.error(error);
          return;
        }
        const deviceName = device.localName ?? device.name;
        if (!deviceName) {
          return;
        }
        if (!(device.id in state.devices)) {
          state.devices[device.id] = deviceName;
        }
      });
      state.isScanning = true;
      state.interval = setInterval(notifyListeners, NOTIFY_INTERVAL_MS);
    })
    .catch((err) => console.error(err));
```

**Comment by bogguard** [comment]
Since Android 12 you'll need the following extra permissions : 
```xml
  <uses-permission android:name="android.permission.BLUETOOTH_CONNECT"/>
  <uses-permission android:name="android.permission.BLUETOOTH_SCAN"/>
```
If you're using the latest expo, you can use the `expo prebuild` with the following `app.json`

```json
{
  "expo": {
    "name": "test-ble",
    "slug": "test-ble",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/icon.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#ffffff"
    },
    "updates": {
      "fallbackToCacheTimeout": 0
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "xxx.xxx.xx"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#FFFFFF"
      },
      "permissions": [
        "android.permission.BLUETOOTH",
        "android.permission.BLUETOOTH_ADMIN",
        "android.permission.BLUETOOTH_SCAN",
        "android.permission.BLUETOOTH_CONNECT",
        "android.permission.ACCESS_COARSE_LOCATION",
        "android.permission.ACCESS_FINE_LOCATION"
      ],
      "package": "xxx.xxx.xxx"
    },
    "web": {
      "favicon": "./assets/favicon.png"
    },
    "plugins": ["@config-plugins/react-native-ble-plx"]
  }
}
```

In your code make sure you request the permissions.
I did this by adding the `react-native-permissions` library to my project and requesting the permissions at runtime.

`package.json`
```json
{
  "name": "test-ble",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "@config-plugins/react-native-ble-plx": "^2.0.0",
    "expo": "~45.0.0",
    "expo-dev-client": "~1.0.1",
    "expo-splash-screen": "~0.15.1",
    "expo-status-bar": "~1.3.0",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-native": "0.68.2",
    "react-native-ble-plx": "^2.0.3",
    "react-native-permissions": "^3.5.0",
    "react-native-web": "0.17.7"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@types/react": "~17.0.21",
    "@types/react-native": "~0.66.13",
    "typescript": "~4.3.5"
  },
  "private": true
```

code snippet : 
```js
   await PermissionsAndroid.request(
    PermissionsAndroid.PERMISSIONS.ACCESS_FINE_LOCATION
  );
  await requestMultiple([
    PERMISSIONS.ANDROID.BLUETOOTH_SCAN,
    PERMISSIONS.ANDROID.BLUETOOTH_CONNECT,
  ]);

  requestBluetoothPermissionAsync()
    .then(() => {
      BluetoothManager.startDeviceScan(null, null, (error, device) => {
        if (error) {
          // Handle error (scanning will be stopped automatically)
          console.error(error);
          return;
        }
        if (device) {
          const deviceName = device.localName ?? device.name;
          if (!deviceName) {
            return;
          }
          if (!(device.id in state.devices)) {
            state.devices[device.id] = deviceName;
          }
        }
      });
      state.isScanning = true;
      state.interval = setInterval(notifyListeners, NOTIFY_INTERVAL_MS);
    })
    .catch((err) => console.error(err));
}
```
